import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import SessionWrapper from './_components/SessionWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={clsx(
            'flex min-h-screen flex-col antialiased',
            inter.className,
          )}
          // TODO remove this before prod
          suppressHydrationWarning={true}
        >
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
